### ISSUE TITLE
13. Factorial - Ranges

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#30]

**Comment by Shruti2791** [comment]
1) Indentation issues.
2) If I enter  '-1' it would return an error message -> 'A non-integer value was entered. Try again'. Is it correct ?
3) Why do we need an extra variable to store result. Can't we directly display it ?

**Comment by osifoanosike** [comment]
Indentation Fixed.
I've added limiting meta-characters to make the regex correct.
Also removed result variable assignment.

**Comment by Shruti2791** [comment]
1) Invalid entries should be checked inside the factorial method itself. This would enable you to reuse this method anywhere else.

**Comment by osifoanosike** [comment]
Ok. I thought since i'm monkey-patching the factorial method on the Fixnum class, the class exceptions already apply to the method. Please enlighten me if i'm wrong. Thanks

**Comment by osifoanosike** [comment]
Validation has been added in factorial logic. Also updated the regex in main.rb to allow for negative values.

**Comment by Shruti2791** [comment]
Fixnum class only ensures that none of its method is called for any string type of argument apart from some of the methods those are defined for strings as well. In case you would try and call any method on strings you would get an exception. But in order to present meaningful message to the user it either needs to be handled or restricted.
Please discuss in case of any confusion.

#### Fix the points below:

---

1) Indentation issues.
2) What if I want to find factorial for a number like this 98765433212345656 ?
3) Why did we raised that error message ?

**Comment by osifoanosike** [comment]
1. Indentation Fixed.
2. The number is automatically converted to a Bignum, as it has exceeded Fixnum's range
3. Exception was raised to check for negative values, as they still belong in the Integer range

**Comment by Shruti2791** [comment]
1) You will not have factorial method defined on Bignum. Though the result will be converted to Bignum if the number becomes big. 
2) Do not raise exception here. Or either create a separate error class to handle this exception. Since you are already handling exception in the same exercise later so better you do not handle it here.

**Comment by osifoanosike** [comment]
I changed my Fixnum class to Integer, so as to allow for Bignum values, however finding the factorial of 98765433212345656 takes a v.long time to process. Is there a way to optimize?

**Comment by Shruti2791** [comment]
yes, you are using inject in your exercise try an alternative for the same.
