### ISSUE TITLE
10. Hash - Inject

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/basicruby#33]

**Comment by Shruti2791** [comment]
1) Exercise is not functional. It returns NoMethodError: undefined method `strip!' for 12345:Fixnum with input [ 1234, 'dsadfs' ]

**Comment by osifoanosike** [comment]
Modified grouping logic. Fixed

**Comment by Shruti2791** [comment]
1) We do not need 'self' in the 'group' method. Try reasoning out as to why I am asking for this.
2) My last comment was to indicate that we are expecting every value in the array to be a string. For now try running the program directly on an array like this [1234, 'dhsfgj', 1234.45] .
3) Keep a better method name instead of 'group'. Method name should reflect the intent of that method.
4) The logic in line 8 and line 9 can be combined.

**Comment by osifoanosike** [comment]
Fixed, except point 2. I don't seem to understand you. You're saying i should validate for string input? Thanks

**Comment by Shruti2791** [comment]
#### Pt 2

Try running your program directly on this array [1234, 234.45, 'sdhfk'].
Lets discuss this

Rest looks good

**Comment by osifoanosike** [comment]
I've updated code logic to evaluate only static input

**Comment by Shruti2791** [comment]
Looks good
Try the same with exercise 9 (Array Hash).

**Comment by osifoanosike** [comment]
Ok. Done
